### ISSUE TITLE
Adminlte template timestamp Form field not showing the date

### ISSUE THREAD

**Issue by yelnyaface** [InfyOmLabs/laravel-generator#390] opened 2017-02-26 17:44 UTC
hi, this is my first time using infyom generator,

I tried generating a table from database, but then realized the edit page timestamp is not showing in the form:

http://prntscr.com/edn10v

**Comment by yehximin** [comment] 2017-02-26 17:56
it seems the form do not support timestamp format YYYY-MM-DD HH:MM:SS,

do anyone know how to make the edit form show YYYY-MM-DD HH:MM:SS? instead of YYYY-MM-DD?

**Comment by mitulgolakiya** [comment] 2019-03-13 06:50
Duplicate of #71

**Closed by mitulgolakiya** 2019-03-13 06:50 UTC
Labels: duplicate
