### ISSUE TITLE
Using Relationships

### ISSUE THREAD

**Issue by gsc89** [InfyOmLabs/laravel-generator#146] opened 2016-05-17 12:57 UTC
Hi all, 

More of a question / discussion than a issue, how are people dealing with multiple hasmany / belongs to many relationships? 

Straight out of the box I generated a bunch of scaffolding based on a database I had setup, things were looking amazing but... relationships? 

I have a items table which has multiple tables relating to it so for example, types, grades, materials, sizes, locations. 

All these items can be bundled into one table using ->with() on the query which is all fine and well but to display this data I am having to use child rows to process data like objects and the pivot data within that object. 

Is there a better way of doing this? at present the scaffolding is great but with it only being used to support 1 table edits I am going to have to spend a long time adding all the relating data in so wondered how you guys work with this sort of data? 

Thanks for any insights.

**Comment by mitulgolakiya** [comment] 2016-05-19 18:53
@gsc89 We already have the issue in a list for relationships. But as people use relationships in various ways. It's really hard to find what kind of scaffold views we should have for each relationship.

so I have backlogged this issue for a while and we are tracking it here: https://github.com/InfyOmLabs/laravel-generator/issues/51

We are trying to find some better way to give relationships more easy and more powerful. so If you have any suggestion, please post it on that issues.

**Comment by mitulgolakiya** [comment] 2016-05-19 18:53
duplicate of #51

**Closed by mitulgolakiya** 2016-05-19 18:53 UTC
