### ISSUE TITLE
Unique on Update Validation!

### ISSUE THREAD

**Issue by NightZpy** [InfyOmLabs/laravel-generator#54] opened 2016-03-08 09:30 UTC
Actually can add this to validation for update:

`'name' => 'unique:table,field,'.$this->id,`

??

**Comment by NightZpy** [comment] 2016-03-08 09:57
In the rules method into UpdateRequest for the model, i add:

`
        $rules = Model::$rules;
        $rules['field'] = $rules['field'] . ',field,' . $this->id;
        return $rules;
` 

And rule in the declaration on the model:

`"field" => "required|between:1,128|unique:table",`

Unique rule must be last in the string.

And, in the edit.blade.php must be add hidden field with the id value and name='id'.

**Comment by mitulgolakiya** [comment] 2016-07-10 16:13
duplicate of https://github.com/InfyOmLabs/laravel-generator/issues/221

**Closed by mitulgolakiya** 2016-07-10 16:13 UTC
Labels: enhancement
