### ISSUE TITLE
What this really needs is a repeating field and repeating sections

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#202] opened 2016-06-14 01:05 UTC
Do you have any ideas on something like this. This seems to be the bottleneck in development so if we could make it easier it would be very useful to everyone. 
Example of what I  am talking about would be.
***SECTIONS EXAMPLE***
> USERS > CRUD
> REPEATING FORM: ROLES
or
> PRODUCTS > CRUD  / HasMany
> REPEATING FORM: PRODUCT_FEATURE_BLOCK / BelongsTo

***FIELDS***
```
    {
        "fieldInput": "image:string",
        "htmlType": "REPEATING",
        "validations": "",
        "searchable": false,
        "fillable": true,
        "primary": index,
        "inForm": true,
        "inIndex": false
    },
```
***OR COMBINED***
```
  {
        "fieldInput": "section:string",
        "htmlType": "REPEATING",
        "validations": "",
        "searchable": false,
        "fillable": true,
        "primary": index,
        "inForm": true,
        "inIndex": false
    },
  {
        "fieldInput": "section_id:integer",
        "htmlType": "REPEATING",
        "validations": "",
        "searchable": false,
        "fillable": true,
        "primary": index,
        "inForm": true,
        "inIndex": false
    },
  {
        "fieldInput": "image:string",
        "htmlType": "REPEATING",
        "validations": "",
        "searchable": false,
        "fillable": true,
        "primary": index,
        "inForm": true,
        "inIndex": false
    },
  {
        "fieldInput": "content:text",
        "htmlType": "REPEATING",
        "validations": "",
        "searchable": false,
        "fillable": true,
        "primary": index,
        "inForm": true,
        "inIndex": false
    },
```

maybe add models to use to make it easier. 

```
  {
        "fieldInput": "feature_id:integer",
        "htmlType": "REPEATING",
        "validations": "",
        "searchable": false,
        "fillable": true,
        "primary": index,
        "inForm": true,
        "inIndex": false,
        "parentModel":'Product',
        "childModel": 'Feature'
    },
```
AND A SELECT FIELD GETTING DATA FROM ANOTHER MODEL
```
  {
        "fieldInput": "roles",
        "htmlType": "MODELSELECT",
        "validations": "",
        "searchable": false,
        "fillable": true,
        "primary": index,
        "inForm": true,
        "inIndex": false,
        "ModelToUse": 'users',
        "ColumnSelector": 'roles'
    },
```

something along the lines of the repeating row you have in your generator html.

**Comment by phillipmadsen** [comment] 2016-06-14 01:18
Anyway this would make this stand out above the others.  Just want to know your thoughts on it.

**Comment by phillipmadsen** [comment] 2016-06-14 01:27
you could even add a level up in the fields file that would make all this easier. example 

fields-file.json:
```
[
{
 "model":"Post",
 "relationship": "Post:BelongsTo:Category",
    {
        "fieldInput": "id:increments",
        "htmlType": "",
        "validations": "",
        "searchable": false,
        "fillable": false,
        "primary": true,
        "inForm": false,
        "inIndex": false
    },
    {
        "fieldInput": "content:text",
        "htmlType": "textarea",
        "validations": "required",
        "searchable": true,
        "inForm": true,
        "inIndex": true
    },
    {
        "fieldInput": "category:string",
        "htmlType": "MODELSELECT",
        "searchable": true,
        "fillable": true,
        "primary": index,
        "inForm": true,
        "inIndex": false,
        "ModelToUse": 'Category',
        "ColumnSelector": 'title'
    },
    {
        "fieldInput": "post_date:dateTime",
        "htmlType": "date"
    },
 },{
 "model":"Category",
 "relationship": "Category:HasMany:Post"
    {
        "fieldInput": "id:increments",
        "htmlType": "",
        "validations": "",
        "searchable": false,
        "fillable": false,
        "primary": true,
        "inForm": false,
        "inIndex": false
    },
  {
        "fieldInput": "title:string",
        "htmlType": "text",
        "searchable": true,
        "fillable": true,
        "primary": index,
        "inForm": true,
        "inIndex": true
    },
    {
        "fieldInput": "content:text",
        "htmlType": "textarea",
        "validations": "required",
        "searchable": true,
        "inForm": true,
        "inIndex": true
    }, 
 }

]



```

**Comment by phillipmadsen** [comment] 2016-06-14 01:35
Maybe a command to generate the fields-file.json framework would be greate also. 

 php artisan infyom:fields-file Post
or 
 php artisan infyom:fields-file:parent-child Category SubCategory

generates category-subcategory.json - skeleton 

```
	[
	{
	"model":"Post",
	"relationship": "Category:HasMany:SubCategory",
		{
		"fieldInput": "id:increments",
		"htmlType": "",
		"validations": "",
		"searchable": false,
		"fillable": false,
		"primary": true,
		"inForm": false,
		"inIndex": false
		},
	},{
	"model":"Category",
	"relationship": "SubCategory:BelongsTo:Category"
		{
		"fieldInput": "id:increments",
		"htmlType": "",
		"validations": "",
		"searchable": false,
		"fillable": false,
		"primary": true,
		"inForm": false,
		"inIndex": false
		},
		{
		"fieldInput": "category_id:integer:unsigned",
		"htmlType": "foreign:index",
		"validations": "",
		"searchable": false,
		"fillable": true,
		"primary": false,
		"inForm": false,
		"inIndex": false
		}
	}
	]
```

**Comment by mitulgolakiya** [comment] 2016-07-10 16:43
@phillipmadsen This can be a part of foreign key & relationships.

**Comment by mitulgolakiya** [comment] 2016-07-10 16:44
duplicate of https://github.com/InfyOmLabs/laravel-generator/issues/51

**Closed** 2016-07-10 16:44 UTC
