### ISSUE TITLE
It's possible use foreign key?

### ISSUE THREAD

**Issue by medeirosrafael** [InfyOmLabs/laravel-generator#220] opened 2016-07-07 14:14 UTC
I tried follow this: https://github.com/mitulgolakiya/laravel-api-generator/issues/68

And, also is possible populate a select with database values?

**Comment by mitulgolakiya** [comment] 2016-07-10 05:51
duplicate of https://github.com/InfyOmLabs/laravel-generator/issues/62

**Closed by mitulgolakiya** 2016-07-10 05:51 UTC
