### ISSUE TITLE
GUI API Generator Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by Erth0** [InfyOmLabs/laravel-generator#407] opened 2017-03-29 11:32 UTC
Error when i use GUI for API Generator + when you do Scaffold Generator nothing is generated 
when i do Api Scaffold Generator is gennerating the files everything except the migration in the migration is only generated :
`<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateTestsTable extends Migration
{

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tests', function (Blueprint $table) {
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('tests');
    }
}
`
without adding the fields there any help

**Comment by mitulgolakiya** [comment] 2017-05-20 10:45
duplicate of #408

**Closed by mitulgolakiya** 2017-05-20 10:45 UTC
