### ISSUE TITLE
Access Swagger UI

### ISSUE THREAD

**Issue by LordRahl90** [InfyOmLabs/laravel-generator#511] opened 2017-11-20 20:53 UTC
Please how do i access the generated swagger UI????
Thanks

**Comment by skys215** [comment] 2017-11-21 07:21
`infyom/swagger-generator` will only insert swagger style comments in the generated source code. It won't generate any page that let you allow to see the apis.
So you need to:
1. Install [Swaggervel](https://github.com/slampenny/Swaggervel)
`composer require slampenny/Swaggervel=dev-master`
2. After installing, add `Jlapp\Swaggervel\SwaggervelServiceProvider::class` in to provider section in `config/app.php`.
3. Run `php artisan vendor:publish --provider="Jlapp\Swaggervel\SwaggervelServiceProvider"`
4. Now you can see routes in the `php artisan route:list`, which is `/docs` and `/api/docs`

AFAIK, Swaggervel is not compatible with Laravel 5.4 and above yet. You need to remove the `\Blade::setContentTags` and `\Blade::setEscapedContentTags` from `vendor/jlapp/swaggervel/src/Jlapp/Swaggervel/routes.php`

When I used swaggervel first time, there's a bug with the document of the generated model file if I has run the `vendor:publish infyom/laravel-generator`. The definition of the model was not generated. I don't know it has fixed or not.

**Comment by mitulgolakiya** [comment] 2017-11-21 10:13
#413 duplicate of

**Closed by mitulgolakiya** 2017-11-21 10:13 UTC
