### ISSUE TITLE
Searching more than 1 Column - Datatable

### ISSUE THREAD

**Issue by rebootcode** [InfyOmLabs/laravel-generator#397] opened 2017-03-03 02:47 UTC
Currently there is only 1 search box. how can we search data for 2 column at a time.

For example "name" and "city" ( John , Newyork ) in data table list generated by scaffold generator.

**Comment by yehximin** [comment] 2017-03-03 12:57
infyom almost never reply, for your case I think u should ask ur question at:
https://github.com/yajra/laravel-datatables

**Comment by mitulgolakiya** [comment] 2017-03-04 04:35
@rebootcode track it here https://github.com/InfyOmLabs/laravel-generator/issues/388

**Comment by mitulgolakiya** [comment] 2017-03-04 04:35
duplicate of https://github.com/InfyOmLabs/laravel-generator/issues/388

**Closed by mitulgolakiya** 2017-03-04 04:35 UTC
