### ISSUE TITLE
Problem with routes

### ISSUE THREAD

**Issue by wellescastro** [InfyOmLabs/laravel-generator#64] opened 2016-03-13 17:03 UTC
First of all, sorry for my bad english. So, when i was using the scaffold generator from tables i realized that  the generated routes are outside of the middleware. This can cause errors in views with $errors variable.

**Comment by mitulgolakiya** [comment] 2016-03-13 19:05
we already have it in list. Duplicate of #27

**Closed** 2016-03-13 19:05 UTC
Labels: duplicate
