### ISSUE TITLE
Found a package with easy Relationships

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#196] opened 2016-06-08 18:44 UTC
it still need a lot of functionality but it has relationships and ajax for content retrieval.

Take a look seems pretty simple.

https://github.com/evercode1/view-maker#makeparent-child

look at the following commands the rest are not really helpful at all. why would anyone want a crud that is so hard to add more fields to. all it uses is name. its lame.

But we could rebuild some of it so It actually works and is useful

>  make:chart   =  php artisan make:chart Widget

we would need to make it so we can tell it the fields to use from the table but it is pretty cool. 

### THESE ARE THE TWO COOL ONES
> make:parent-child
> make:child-of

That would be the equivalent to generating a full crud for each and then building in the realtionships which can take some time. 

> example use would be ***Category*** and ***Subcategory***

Both the parent model and the child model will be built with the relationship made for you. The parent will have a has many relationship and the child will have a belongsTo relationship in the model.

**Comment by mitulgolakiya** [comment] 2016-07-10 16:42
@phillipmadsen Ok, Thanks. will consider it while creating relationships.

**Comment by mitulgolakiya** [comment] 2016-07-10 16:42
duplicate of https://github.com/InfyOmLabs/laravel-generator/issues/51

**Closed by mitulgolakiya** 2016-07-10 16:42 UTC
