### ISSUE TITLE
is this package supports laravel 5.4

### ISSUE THREAD

**Issue by adnanmayo** [InfyOmLabs/laravel-generator#417] opened 2017-05-01 16:14 UTC
Hi I have been using this package in laravel 5.2. it works really well. In its documentation, it has only 5.3.

**Comment by Konrad90** [comment] 2017-05-02 21:41
Check here https://github.com/InfyOmLabs/laravel-generator/issues/382

**Comment by mitulgolakiya** [comment] 2017-05-20 10:36
support for laravel 5.4 added. duplicate of #382

**Closed by mitulgolakiya** 2017-05-20 10:36 UTC
