### ISSUE TITLE
Scaffolding: generated routes should be placed inside "web" middleware group

### ISSUE THREAD

**Issue by pjmartorell** [InfyOmLabs/laravel-generator#45] opened 2016-03-03 12:00 UTC
Generating a scaffold should place the generated routes inside "web" middleware group in order to make the "$errors" variable to be binded correctly in the views.

**Comment by mitulgolakiya** [comment] 2016-03-04 03:47
duplicate of #27

**Closed** 2016-03-04 03:48 UTC
Labels: duplicate
