### ISSUE TITLE
problem with date field

### ISSUE THREAD

**Issue by kirchaj** [InfyOmLabs/laravel-generator#136] opened 2016-05-10 13:03 UTC
I have created a crud table with two date fields.  When I enter data into the create form I end up with the following error

InvalidArgumentException in Carbon.php line 425: Unexpected data found.
Unexpected data found.
Data missing

 in Carbon.php line 425
at Carbon::createFromFormat('Y-m-d H:i:s', '05/10/2016') in Model.php line 2958
at Model->asDateTime('05/10/2016') in Model.php line 2912
at Model->fromDateTime('05/10/2016') in Model.php line 2867
at Model->setAttribute('order_date', '05/10/2016') in Model.php line 447
at Model->fill(array('_token' => 'SqlT8jFPpWtMMULnd56QhR47x5NDW75rkkD8qhZj', 'ticket_num' => '789jklh;lk', 'customer_id' => '4', 'status' => '1', 'order_date' => '05/10/2016', 'required_date' => '05/10/2016', 'complete_date' => '05/10/2016', 'summary' => 'aksdj;flaksjd;flkajsd;lfkjasd;lfkjas;dflkjas;dlfkjas;ldkfja;sldkjf;aslkdjf;asldkjfa;sd')) in Model.php line 281

**Comment by kirchaj** [comment] 2016-05-10 15:30
ok, this was caused by a date entry issue.  I had entered 05/10/2016 and it really wanted 2015-05-10.

**Comment by mitulgolakiya** [comment] 2016-05-11 18:45
duplicate of #71

**Closed by mitulgolakiya** 2016-05-11 18:45 UTC
