### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#195] opened 2016-06-08 02:40 UTC
Have you been able to make any progress on the input file yet.  such as move to public folder function so when we use the output {!! $crud->image !!} it actually outputs the usable file?

**Comment by mitulgolakiya** [comment] 2016-06-25 06:26
No. Not yet.

**Comment by mitulgolakiya** [comment] 2016-06-25 06:26
Duplicate of https://github.com/InfyOmLabs/laravel-generator/issues/1

**Closed by mitulgolakiya** 2016-06-25 06:26 UTC
