### ISSUE TITLE
parent-child relation

### ISSUE THREAD

**Issue by jrodpardo** [InfyOmLabs/laravel-generator#349] opened 2016-11-18 15:52 UTC
Hi guys,
I need help with relationships. This could be related to issue #51???
Datatables doesn't allow me to explode into the parent's children (no icon to click in order to view the children).
Yes, I have a parent with children in the database....
What is that I'm missing???
Please help.

command line scaffolds:
php artisan infyom:scaffold xparent --fieldsFile='resources/model_schemas/xparent.json' --datatables=true
php artisan infyom:scaffold xchild  --fieldsFile='resources/model_schemas/xchild.json'  --datatables=true

xparent.json schema:
[
    {
        "name": "id",
        "dbType": "increments",
        "htmlType": "",
        "validations": "",
        "searchable": false,
        "fillable": false,
        "primary": true,
        "inForm": false,
        "inIndex": false
    },
    {
        "name": "name",
        "dbType": "string,32",
        "htmlType": "text",
        "validations": "required",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true
    },...
  

xchild.json schema:
  [
    {
        "name": "id",
        "dbType": "increments",
        "htmlType": "",
        "validations": "",
        "searchable": false,
        "fillable": false,
        "primary": true,
        "inForm": false,
        "inIndex": false
    },
    {
        "name": "name",
        "dbType": "string,32:unique",
        "htmlType": "text",
        "validations": "required",
        "searchable": true
    },
    {
        "name": "parent_id",
        "dbType": "integer:unsigned:foreign,xparents,id",
        "htmlType": "text",
        "relation": "mt1,xparent,parent_id,id"
        
    },...

Thanks!

**Comment by th3d0g** [comment] 2016-11-22 10:47
I'm also looking to be able to list and edit child objects from a parents view. Is this even supported?

If not, what's the best approach to extending the generator to support this?

**Comment by ShaileshInfyom** [comment] 2022-01-28 09:48
@th3d0g Generator not supported for Relationship in view. The issue is already open here https://github.com/InfyOmLabs/laravel-generator/issues/731. So, I marked it as a duplicate and closed it. Thanks for your time. if you think your issue is different then feel free to re-open the issue with more details if you are still facing this issue.

**Closed by ShaileshInfyom** 2022-01-28 09:48 UTC
