### ISSUE TITLE
can we have a means of not generating fields for certain columns?

### ISSUE THREAD

**Issue by vesper8** [InfyOmLabs/laravel-generator#79] opened 2016-03-20 15:26 UTC
The created_at, updated_at and deleted_at all should never have a field in the create/edit view. Those are handled by Laravel and aren't meant to be added or modified manually.

Maybe we could have something in the config/generator.php where we can specify which columns to not generate fields for for the create/edit views? I've been find/replacing them manually for now.

**Comment by mitulgolakiya** [comment] 2016-03-26 10:16
With the latest code, created_at and updated_at are not added in forms anymore. And we are going give the option to specify if a field should be added in index and form.

Check the branch https://github.com/InfyOmLabs/laravel-generator/tree/35_include_in_index_form

duplicate of #35

**Closed** 2016-03-26 10:16 UTC
Labels: duplicate, enhancement

**Comment by vesper8** [comment] 2016-05-07 15:42
I'm using latest code with datatables and created_at, updated_at and deleted_at are still added to the edit form!!

What's worse, when you edit an entry it automatically populates deleted_at with zeros which then causes it not to show up in the list!!!!!

I've asked for a means to have those 3 fields not appear in forms, your answer to this was to add the ability to have fields not show up in form when using the schema.json file.

But what about those of us that don't use that file? I always generate my schemas from existing table.

I would like to be able to configure the laravel_generator.php configuration file in which I could say which fields to never show up in forms.

I still want my model to use these timestamp fields, they just have no business appearing in the create/edit forms!
