### ISSUE TITLE
field type question

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#30] opened 2016-02-22 20:01 UTC
Can you add a checkbox field for boolean?  with option for default unchecked.

**Comment by phillipmadsen** [comment] 2016-02-24 17:40
Do you by chance have a way to generate boolean checkbox?

**Comment by mitulgolakiya** [comment] 2016-02-25 03:29
Will add it.

**Comment by mitulgolakiya** [comment] 2016-03-26 10:25
Duplicate of #88

**Closed by mitulgolakiya** 2016-03-26 10:25 UTC
Labels: duplicate, enhancement, in progress
