### ISSUE TITLE
Need Template Assets publish command

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#125] opened 2016-04-28 19:38 UTC
As of right now I  do not see a way to publish assets required for the tempates into the public folder. 

Also need to be able to publish them into a theme or layout directory to keep it clean and so it is only used for that layout / theme.

Am I  missing it or is this just no built in yet?

**Comment by phillipmadsen** [comment] 2016-04-28 19:46
```
|- resources
    |- views
        |- {{THEME / LAYOUT NAME }}
          |- layouts
              |- app.blade.php
              |- menu.blade.php
              |- sidebar.blade.php
          |- emails
              |- password.blade.php
          |- auth
              |- login.blade.php
              |- register.blade.php
              |- reset.blade.php
              |- password.blade.php
|- public
    |- {{THEME / LAYOUT NAME }}
        |- images
        |- css
        |- js
        
```

**Comment by mitulgolakiya** [comment] 2016-05-07 06:22
duplicate of #124

**Closed by mitulgolakiya** 2016-05-07 06:22 UTC
