### ISSUE TITLE
Override generateScaffoldItems function

### ISSUE THREAD

**Issue by littlecxm** [InfyOmLabs/laravel-generator#566] opened 2018-09-14 07:36 UTC
I regist it in my povider 
```php
public function register()
    {
        //
        $this->app->booting(function() {
            $loader = AliasLoader::getInstance();
            $loader->alias('InfyOm\Generator\Commands\BaseCommand','App\Overrides\MyOverrideClass');
        });
    }
```
```php
public function generateScaffoldItems()
    {
        //override...
    }
```
But it didn't worked.
Is it possible or maybe exist a better way to override this function?

**Comment by mitulgolakiya** [comment] 2019-03-18 12:31
Duplicate of #92

**Closed by mitulgolakiya** 2019-03-18 12:31 UTC
Labels: duplicate
