### ISSUE TITLE
Include page no., page links, and totals in api response using pagination

### ISSUE THREAD

**Issue by perezale** [InfyOmLabs/laravel-generator#418] opened 2017-05-04 00:34 UTC
Hi!!

I've read  #264 and I was looking for exactly the same thing this guy does not want.
I noticed that nowadays api generator applies LimitOffsetCriteria for paged queries, which uses _limit_ and _skip_ Model operations. This is is nice but it wont output pagination data, like: current page no. , total, link page, etc.
I would like to keep using LimitOffsetCriteria but include pagination data (the same output as Luciano's original message)

`"success": true,
  "data": {
    "total": 10,
    "per_page": 10,
   ...
   "data": [
      {...},
      {...},
      {...},
   ]
},
"message": ""
`
Any ideas on how should I proceed? When trying to keep only data items they talked about ResponseUtil but I cannot see how it could help me now.

Note; If I change my generated api controllers to use paginate($limit ..) the response is as expected. But its not what I want.

Thanks in advance

**Comment by mitulgolakiya** [comment] 2018-12-07 02:58
duplicate of https://github.com/InfyOmLabs/laravel-generator/issues/264#issuecomment-444884727

**Closed by mitulgolakiya** 2018-12-07 02:58 UTC
Labels: feature
