### ISSUE TITLE
Select html type: Bug or new feature!

### ISSUE THREAD

**Issue by NightZpy** [InfyOmLabs/laravel-generator#53] opened 2016-03-08 07:51 UTC
When generate a select field, is obligatory add items to select list:

> select-field-name:option1,2,3

Maybe, i don't want add statis list item, because the select will be filled from another database table!

This may be a new feature or just a bug?

**Comment by mitulgolakiya** [comment] 2016-03-09 06:20
duplicate of #57

**Closed by mitulgolakiya** 2016-03-09 06:20 UTC
Labels: duplicate, feature
