### ISSUE TITLE
core-templates error because of web middleware

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/laravel-generator#27] opened 2016-02-22 18:57 UTC
@include('core-templates::common.errors') 

returns this:

ErrorException in 738befae3e778accfa7edc7bda672348bdebf4da.php line 1:
Undefined variable: errors (View: /home/vagrant/grace/blade.clip/vendor/infyomlabs/core-templates/views/common/errors.blade.php) (View: /home/vagrant/grace/blade.clip/vendor/infyomlabs/core-templates/views/common/errors.blade.php)

**Comment by mitulgolakiya** [comment] 2016-02-22 19:38
May we you are using Laravel 5.2. So you need to use `web` middleware to get your routes working.
Duplicate of #21

**Closed** 2016-04-12 18:34 UTC
Labels: bug

**Comment by mitulgolakiya** [comment] 2016-04-12 18:39
closed in ref of https://github.com/InfyOmLabs/core-templates/pull/5
