### ISSUE TITLE
[Feature] Missing stub files (and other detail) in 9.0 and 8.0 with locale and datatables scaffold

### ISSUE THREAD

**Issue by magojr** [InfyOmLabs/laravel-generator#997] opened 2022-03-21 11:16 UTC
I tried to go for a new project with 9.0 and I found:
-Missing Boilerplates (linked from the documentation) for Adminlte https://github.com/InfyOmLabs/adminlte-generator/tree/9.0 bring to a 404 (with /8.0 is present the 8 version)
-Installing the AdminLTE + Datatables:
  -Missing some stubs about "locale" and "datatables" scaffold generation
  -Missing documentation about the right version of datatables-button to use with dependencies of 9.0, that is 5.0
  -Random error generating assets ( Sometimes "npm install && npm run dev" bring to a generic error but clearing modules and cache, sometimes it works, very strange behaviour).

Now I tried cloning boilerplate 8.0 that is working but with "--jqueryDT" ther's another missing stub:
"vendor/infyomlabs/adminlte-templates/templates/scaffold/views/js_index.stub"

Last detail, I found that datatables usage bring to loose some correct AdminLTE padding making the datatables content stck to the template border.

Hope this may help in solving these issues.

**Comment by mitulgolakiya** [comment] 2022-04-12 04:14
As per this comment, we are moved with our own package of laravel-ui-adminlte. so localization is pending. Mentioned in this comment https://github.com/InfyOmLabs/laravel-generator/issues/991#issuecomment-1072936740

We are not sure, how to support it yet, But soon we will try to add it.

Suggestions or any PRs are welcomed from the community.

**Comment by mitulgolakiya** [comment] 2022-04-12 04:15
Duplicate of https://github.com/InfyOmLabs/adminlte-templates/issues/82

**Comment by mitulgolakiya** [comment] 2022-07-24 10:16
Localization support is added in v5.1.0.

**Closed as completed by mitulgolakiya** 2022-07-24 10:16 UTC
Labels: feature
