### ISSUE TITLE
File not getting upload

### ISSUE THREAD

**Issue by veed76** [InfyOmLabs/laravel-generator#710] opened 2019-08-26 06:10 UTC
Hi @mitulgolakiya 

Thank you for this awesome generator.
Here, I have an api_scaffold "Influencer". In **model_schemas/Influencer.json** I added all these fields.

```
{
        "name": "vendor_name",
        "dbType": "string",
        "htmlType": "text",
        "validations": "required",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true
    },
    {
        "name": "vendor_image",
        "dbType": "string:nullable",
        "htmlType": "file",
        "validations": "",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true
    },
```

After performing the migration, I see the CRUD in the admin panel.
I created one record with uploading **vendor_image** and the record successfully created: https://prnt.sc/oxidzo. I checked the storage directory but I can't see the **vendor_image** inside storage directory. For file uploading is there any configuration?

**Comment by mitulgolakiya** [comment] 2019-08-26 12:54
@veed76 Thanks. But right now generator does not support file upload by default. You need to modify your controllers + repository by your self to handle file upload.

**Comment by mitulgolakiya** [comment] 2019-08-26 12:56
Duplicate of https://github.com/InfyOmLabs/laravel-generator/issues/103

**Closed by mitulgolakiya** 2019-08-26 12:56 UTC
